name: citibike

profile: citibike

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  citibike:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
